routes/web.php
<?php

use Illuminate\Support\Facades\Route;




Route::group(['middleware'=>'auth'],function(){


Route::group(['prefix'=>'manager', 'namespace'=>'Manager'],function(){


    Route::resource('dashboard', 'DashboardController');
    Route::resource('users', 'UserController');

    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::resource('coupon', 'CouponController');
    Route::resource('roles', 'RoleController');

    Route::get('orders', 'OrderManageController@index')->name('manager.orders.index');
    Route::get('orders/{id}', 'OrderManageController@show')->name('manager.orders.show');


});

//client

    // Route::resource('cart', 'CartController');

    // Route::resource('checkout', 'CartController');



});
//


Route::group(['namespace'=>'Client'],function(){

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/products/{id}', 'HomeController@showProduct')->name('client.show_product');

    Route::get('/carts', 'CartController@index')->name('cart.index');

    Route::post('/add-to-cart', 'CartController@addToCart')->name('cart.add_to');

    Route::post('/change-to-cart', 'CartController@changeQuantityCart')->name('cart.change_quantity');

    Route::get('/orders', 'OrderController@index')->name('orders.index');


    Route::post('/add-coupon-order', 'OrderController@addCouponToOrder')->name('orders.add_coupon');


    Route::post('/orders', 'OrderController@store')->name('orders.store');

    Route::get('/order-list', 'OrderController@list')->name('orders.list');


    Route::get('/contact', 'ContactController@index')->name('contact');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::get('/profile-edit', 'ProfileController@edit')->name('profile.edit');
    Route::get('/profile-update', 'ProfileController@update')->name('profile.update');

});

Auth::routes();

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use App\Traits\HandleImageTrait;
use Illuminate\Notifications\Notifiable;
class Product extends Model
{
    use Notifiable;
    use HandleImageTrait;
    protected $table = 'products';


    protected $fillable = [
        'name', 'price', 'sale','image'
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_product', 'product_id', 'category_id');
    }

    public function assignCategories($categoryIds = [])
    {
        return $this->categories()->sync($categoryIds);
    }

    public function addCategories($categoryIds)
    {
        return $this->categories()->attach($categoryIds);
    }

    public function removeCategories($categoryIds)
    {
        return  $this->categories()->detach($categoryIds);
    }


    public function getProductHasCategory($categoryName){

        return $this->whereHas('categories', function ($query) use ($categoryName){
            $query->where('name', $categoryName);
        })
            ->get();
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name','LIKE','%'.$name.'%') :  null;
    }

    public function scopeWithCategoryId($query, $categoryId)
    {
        return $categoryId ? $query->whereHas('categories', function ($q) use ($categoryId) {
            return $q->where('categories.id', $categoryId);
        })
            :  null;
    }

}

app/Http/Controllers/Manager/CategoryController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Models\Category;
use App\Models\Product;
use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use App\Http\Requests\category\CreateCategoryRequest;
use App\Http\Requests\category\UpdateCategoryRequest;
use App\Models\Role;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    protected $categoryModel;
    protected $productModel;


    public function __construct(Category $categoryModel,Product $product,Role $role)
    {
        $this->categoryModel = $categoryModel;
        $this->productModel = $product;
        $this->roleModel = $role;
    }

    public function index()
    {

        $categories = $this->categoryModel->with(['childCategories', 'parentCategories'])
            ->latest('id')->paginate(5);

        return view('manager.category.index', compact('categories'));

    }


    public function create()
    {
        $categories =  $this->categoryModel->get(['id', 'name']);

        return view('manager.category.create', compact('categories'));


    }



    public function store(Request $request)
    {
        $dataCreate =  $request->all();
        $this->categoryModel->create($dataCreate);

        return redirect()->route('category.index')->with('message', 'Create category success');

    }


    public function show($id)
    {
        $category = $this->categoryModel->findOrFail($id);

        return  response()->json([
            'status'=>200,
            'data' =>new CategoryResource($category)
        ]);

    }




    public function edit($id)
    {
       $category= Category::findOrFail($id);
        $categories = $this->categoryModel->get(['id','name']);
        return view('manager.category.edit')->with(['category'=> $category,'categories'=>$categories]);
    }

    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);


        $dataUpdate = $request->all();


        $category->update($dataUpdate);

        return redirect()->route('category.index')->with('message', 'Edit category success');
    }


    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect()->route('category.index')->with('message', 'Delete category success');
    }
}

app/Http/Controllers/Manager/CouponController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Http\Requests\Coupon\CreateCouponRequest;
use App\Http\Requests\Coupon\UpdateCouponRequest;
use App\Traits\HandleImageTrait;
use App\Models\User;
use App\Models\Coupon;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;


class CouponController extends Controller
{
    public function index()
    {
        $coupons = Coupon::paginate(3);

        return view('manager.coupon.index')->with( 'coupons',$coupons);
    }


    public function create()
    {
        return view('manager.coupon.create');

    }

    public function store(Request  $request)
    {

        $dataCreate = $request->all();

        Coupon::create($dataCreate);

        return redirect()->route('coupon.index')->with('message', 'Create coupon success');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $coupon = Coupon::findOrFail($id);

        return view('manager.coupon.edit')->with('coupon', $coupon);
    }


    public function update(Request  $request, $id)
    {
        $coupon = Coupon::findOrFail($id);


        $dataUpdate = $request->all();


        $coupon->update($dataUpdate);

        return redirect()->route('coupon.index')->with('message', 'Edit coupon success');
    }

    public function destroy($id)
    {
        $coupon = Coupon::findOrFail($id);
        $coupon->delete();

        //Thực hiện chuyển trang
        return redirect()->route('coupon.index')->with('message', 'Delete coupon success');
    }
}

app/Http/Controllers/Manager/DashboardController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Coupon;
use App\Models\Order;
use App\Models\Product;
use App\Traits\HandleImageTrait;
use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    use HandleImageTrait;

    protected $categoryModel;
    protected $productModel;
    protected $userModel;
    protected $couponModel;
    protected $orderModel;


    public function __construct(Product $product,Category $categories, User $user, Coupon $coupons, Order $orders)
    {

        $this->categoryModel = $categories;
        $this->productModel = $product;
        $this->userModel = $user;
        $this->couponModel = $coupons;
        $this->orderModel = $orders;

    }

    public function index()
    {


        $products =  $this->productModel->count();
        $categories = $this->categoryModel->count();
        $user = $this->userModel->count();
        $coupons = $this->couponModel->count();
        $orders = $this->orderModel->count();

        return view('manager.dashboard.index', compact('products','user','categories','coupons','orders'));

    }

}

app/Http/Controllers/Manager/OrderManageController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\Category;
use App\Models\Coupon;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\Product;
use Illuminate\Http\Request;

class OrderManageController extends Controller
{
    protected  $categoryModel;
    protected  $productModel;
    protected  $cart;
    protected  $coupon;
    protected  $order;
    protected  $orderDetail;


    public function __construct(Category $categoryModel,Product $product, Cart $cart, Coupon $coupon, Order $order, OrderDetail $orderDetail)
    {
        $this->categoryModel = $categoryModel;
        $this->productModel = $product;
        $this->cart = $cart;
        $this->coupon = $coupon;
        $this->orderDetail = $orderDetail;
        $this->order = $order;
    }

    public function index(Request $request)
    {
        $orders = $this->order->with(['orderDetails'])->latest('id')->paginate(10);

        return view('manager.order.index', compact('orders'));
    }

    public function show($id)
    {
        $order = $this->order->with(['orderDetails', 'orderDetails.product'])->findOrFail($id);

        return view('manager.order.show', compact('order'));
    }
}

app/Http/Controllers/Manager/ProductController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Traits\HandleImageTrait;
use App\Models\Product;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Str;


class ProductController extends Controller
{
    use HandleImageTrait;

    protected $path;
    protected $categoryModel;
    protected $productModel;



    public function __construct(Product $product,Category $categoryModel)
    {

        $this->categoryModel = $categoryModel;
        $this->productModel = $product;
        $this->path = 'upload/';
    }

    public function index(Request  $request)
    {
        $data['name'] = $request->name ?? null;
        $data['category_id'] = $request->category_id ?? null;

        $products =  $this->productModel->withName($data['name'])
            ->withCategoryId($data['category_id'])
            ->with(['categories'])
            ->latest('id')->paginate(5);


        return view('manager.product.index', compact('products'));

    }

    public function create()
    {
        $categories =  $this->categoryModel->get(['id', 'name']);

        return view('manager.product.create', compact('categories'));


    }


    public function store(Request  $request)
    {
        $image = $request->file('image');
        $dataCreate =  $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $product = $this->productModel->create($dataCreate);

        $product->assignCategories($dataCreate['category_ids']);

        return redirect()->route('product.index')->with('message', 'Create product success');

    }


    public function show($id)
    {


    }


    public function edit($id){
        $product = $this->productModel->with(['categories'])->findOrFail($id);
        $categories = $this->categoryModel->get();
        $listCategoryIds = $product->categories->pluck('id')->toArray();
        return view('manager.product.edit')->with(['product'=> $product,'categories'=>$categories,'listCategoryIds'=>$listCategoryIds]);
    }




    public function update(Request $request, $id)
    {
        $product = $this->productModel->findOrFail($id);
        $image = $request->file('image');
        $dataUpdate = $request->all();
        $dataUpdate['image'] = $this->updateImage($image, $this->path, $product->image);
        $product->update($dataUpdate);
        $product->assignCategories($request -> listCategoryIds);
        return redirect()->route('product.index')->with('message', 'Edit product success');
    }

    public function destroy($id)
    {
        $product = $this->productModel->findOrFail($id);
        $product->delete();

        //Thực hiện chuyển trang
        return redirect()->route('product.index')->with('message', 'Delete product success');
    }
}

app/Http/Controllers/Manager/RoleController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Coupon;
use Illuminate\Http\Request;
use App\Models\Role;

class RoleController extends Controller
{
    protected $roleModel;

    /**
     * RolerController constructor.
     * @param $roleModel
     */

    public function __construct(Role $roleModel)
    {
        $this->roleModel = $roleModel;
    }


    public function index()
    {
        $roles = $this->roleModel->where('name','!=', 'super-admin')->paginate(5);

        return view('manager.role.index')->with( 'roles',$roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manager.role.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dataCreate = $request->all();

        Role::create($dataCreate);

        return redirect()->route('roles.index')->with('message', 'Create role success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Traits\HandleImageTrait;
use App\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    use HandleImageTrait;

    protected $path;
    protected $roleModel;

    protected $userModel;

    public function __construct(User $user, Role $role)
    {
        $this->userModel = $user;
        $this->path = 'upload/';
        $this->roleModel = $role;
    }



    public function index()
    {

        $users = $this->userModel->with('roles')->latest('id')->paginate(5);

        return view('manager.user.index')->with( 'users',$users);

    }


    public function create()
    {
        $roles = $this->roleModel->where('name', '!=', 'super-admin')->get();
        return view('manager.user.create', compact('roles'));
    }


    public function store(CreateUserRequest $request)
    {

        $image = $request->file('image');

        $dataCreate = $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $user =$this->userModel->create($dataCreate);
        $user->syncRoles($request->roles);
        return redirect()->route('users.index')->with('message', 'Create user success');
    }


    public function show($id)
    {
        //
    }



    public function edit($id)
    {
        $user = $this->userModel->with('roles')->findOrFail($id);

        $roles = $this->roleModel->where('name', '!=', 'super-admin')->get();
        $listRoleIds = $user->roles->pluck('id')->toArray();
        return view('manager.user.edit')->with(['user'=> $user, 'roles' =>$roles, 'listRoleIds' =>$listRoleIds]);
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $user = $this->userModel->findOrFail($id);
        $image = $request->file('image');

        $dataUpdate = $request->all();

        $dataUpdate['image'] = $this->updateImage($image, $this->path, $user->image);

        $user->update($dataUpdate);
        $user->syncRoles($request->roles);
        return redirect()->route('users.index')->with('message', 'Edit user success');

    }


    public function destroy($id)
    {
        $users = $this->userModel->findOrFail($id);
        $users->delete();

        //Thực hiện chuyển trang        //Thực hiện chuyển trang
        return redirect()->route('users.index')->with('message', 'Delete user success');
    }
}

resources/views/manager/product/create.blade.php
@extends('manager.layout.app')

@section('title', 'Create Products')

@section('content')
    <a class="btn btn-rose " href="{{route('product.index')}}">
      <span class="material-icons text-white">
        arrow_back
      </span>
    </a>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon">
                        <span class="material-icons">
                            inventory_2
                            </span>
                    </div>
                    <h4 class="card-title">Create Product</h4>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('product.store') }}"  enctype="multipart/form-data">
                        @csrf


                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <h4 class="title">Regular Image</h4>
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{asset('manager/asset/img/image_placeholder.jpg')}}" alt="...">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                              <span class="btn btn-rose btn-round btn-file">
                                                <span class="fileinput-new">Select image</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input type="file" name="image">
                                              </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        </div>



                        <div class="form-group row">
                            <div class="col-md-6">
                                <input id="name" type="text" placeholder="{{ __('name') }}" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}"  autocomplete="name" autofocus required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6">
                                <input id="sale" type="text" placeholder="{{ __('sale') }}" class="form-control @error('sale') is-invalid @enderror" name="sale" value="{{ old('sale') }}"  autocomplete="sale" autofocus required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Categories') }}</label>

                            <div class="col-md-6">
                                <select class="selectpicker" data-live-search="true" name="category_ids[]" multiple
                                        title="choose categories"
                                        data-style="select-with-transition" >
                                    @foreach($categories as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>



                        <div class="form-group row">
                            <div class="col-md-6">
                                <input id="price" type="text" placeholder="{{ __('price') }}" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}"  autocomplete="price" autofocus required>

                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-rose">
                                    {{ __('Create Product') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/product/edit.blade.php
@extends('manager.layout.app')

@section('title', 'Edit Products')

@section('content')
    <a class="btn btn-rose "href="{{route('product.index')}}">
      <span class="material-icons text-white">
        arrow_back
      </span>
    </a>
    <div class="row justify-content-center">
        <div class="col-md-12 ">
            <div class="card ">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon">
                        <span class="material-icons">
                            inventory_2
                            </span>
                    </div>
                    <h4 class="card-title">Edit Product</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('product.update', $product->id) }}"  enctype="multipart/form-data">
                        @csrf
                        @method('put')


                        <div class="row">
                            <div class="col-md-4 col-sm-4">
                                <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                                    <div class="fileinput-new thumbnail">
                                        <img src="{{asset('upload/'.$product->image)}}" alt="...">
                                    </div>
                                    <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                    <div>
                                              <span class="btn btn-rose btn-round btn-file">
                                                <span class="fileinput-new">Select image</span>
                                                <span class="fileinput-exists">Change</span>
                                                <input type="file" name="image">
                                              </span>
                                        <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>




                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $product->name }}"  autocomplete="name" autofocus required>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="sale" class="col-md-4 col-form-label">{{ __('sale') }}</label>

                            <div class="col-md-6">
                                <input id="sale" type="text" class="form-control @error('sale') is-invalid @enderror" name="sale" value="{{ $product->sale }}"  autocomplete="sale" autofocus required>

                            </div>
                        </div>





                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label">{{ __('price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $product->price }}"  autocomplete="price" autofocus>

                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label">{{ __('Categories') }}</label>
                            <div class="col-md-6">
                                <select class="selectpicker" data-live-search="true" name="listCategoryIds[]" multiple data-style="select-with-transition" >
                                    @foreach($categories as $item)
                                        <option value="{{$item->id}}"   {{ in_array($item->id, $listCategoryIds) ? 'selected' : ''  }}    >{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-rose">
                                    {{ __('Edit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/product/index.blade.php
@extends('manager.layout.app')

@section('title', 'Products')

@section('content')



    <h1 class="text-center" style="color: #e91e63; margin-bottom: 50px; ; font-weight: 400;">LIST PRODUCTS</h1>
    <div class="col-md-12">
        <form action="{{route('product.index')}}" method="get" class="w-100">
            <div class="row">
                <div class="col-3">
                    <input type="text" placeholder="Name search" class="form-control" value="{{request('name')}}" name="name" >
                </div>
                <div class="col-3">
                    <select name="category_id" class="selectpicker" data-style="select-with-transition"  >
                        <option value="">Category</option>
                        @foreach($categories as $item)
                            <option value="{{$item->id}}"  {{$item->id == request('category_id') ?'selected' : ''}} >{{$item->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-3">
                    <button class="btn btn-rose" type="submit"> search</button>
                </div>
            </div>
        </form>
        <a class="btn btn-rose" href="{{route('product.create')}}"><span class="material-icons">
            add_circle_outline 
            </span> Create Product</a>
        <div class="card">
          <div class="card-header card-header-rose card-header-icon">
            <div class="card-icon"> 
              <i class="material-icons">assignment</i>
            </div>
            <h4 class="card-title">Product Table</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th class="text-center">N.o</th>
                    <th>Name</th>
                    <th>Category Name</th>
                    <th>Sale</th>
                    <th>Price</th>
                    <th class="text-right">Image</th>
                    <th class="text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
            @foreach($products as $product)
                  <tr>
                    <td class="text-center">{{$loop->iteration}}</td>
                    <td>{{$product->name}}</td>
                    <td>
                        @if($product->categories->count() > 0)
                        @foreach($product->categories as $category)
                            {{$category->name}} <br>
                        @endforeach
                    @else
                        <h3>There is no category </h3>
                    @endif    
                    </td>
                    <td>{{$product->sale}}</td>
                    <td> {{$product->price}}</td>
                    <td class="td-actions text-right">
                        <img width="100px" height="100px" src="{{asset('upload/'.$product->image)}}" alt="Anh">
                    </td>
                    <td class="td-actions text-right">
                    <a class="btn btn-success" href="{{route('product.edit', $product->id)}}"><i class="material-icons">edit</i></a>
                    <form action="{{route('product.destroy', $product->id)}}"  method="post" style="display: inline">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger " type="submit"style="background-color: #e91e63"><i class="material-icons">close</i></button>
    
                    </form>
                    </td>
                  </tr>
            @endforeach
                  
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    





    <script>

        @if(session('message'))
        alert("{{session('message')}}");
        @endif
    </script>
    <div>
        {{ $products->links() }}
    </div>

@endsection