routes/web.php
<?php

use Illuminate\Support\Facades\Route;




Route::group(['middleware'=>'auth'],function(){


Route::group(['prefix'=>'manager', 'namespace'=>'Manager'],function(){


    Route::resource('dashboard', 'DashboardController');
    Route::resource('users', 'UserController');

    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::resource('coupon', 'CouponController');
    Route::resource('roles', 'RoleController');

    Route::get('orders', 'OrderManageController@index')->name('manager.orders.index');
    Route::get('orders/{id}', 'OrderManageController@show')->name('manager.orders.show');


});

//client

    // Route::resource('cart', 'CartController');

    // Route::resource('checkout', 'CartController');



});
//


Route::group(['namespace'=>'Client'],function(){

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/products/{id}', 'HomeController@showProduct')->name('client.show_product');

    Route::get('/carts', 'CartController@index')->name('cart.index');

    Route::post('/add-to-cart', 'CartController@addToCart')->name('cart.add_to');

    Route::post('/change-to-cart', 'CartController@changeQuantityCart')->name('cart.change_quantity');

    Route::get('/orders', 'OrderController@index')->name('orders.index');


    Route::post('/add-coupon-order', 'OrderController@addCouponToOrder')->name('orders.add_coupon');


    Route::post('/orders', 'OrderController@store')->name('orders.store');

    Route::get('/order-list', 'OrderController@list')->name('orders.list');


    Route::get('/contact', 'ContactController@index')->name('contact');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::get('/profile-edit', 'ProfileController@edit')->name('profile.edit');
    Route::get('/profile-update', 'ProfileController@update')->name('profile.update');

});

Auth::routes();

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;


class Coupon extends Model
{
    use Notifiable;

    protected $table = 'coupons';

    protected $fillable = [
        'code', 'expiry_date', 'quantity', 'type', 'value',
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];


    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Manager/CategoryController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Models\Category;
use App\Models\Product;
use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use App\Http\Requests\category\CreateCategoryRequest;
use App\Http\Requests\category\UpdateCategoryRequest;
use App\Models\Role;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    protected $categoryModel;
    protected $productModel;


    public function __construct(Category $categoryModel,Product $product,Role $role)
    {
        $this->categoryModel = $categoryModel;
        $this->productModel = $product;
        $this->roleModel = $role;
    }

    public function index()
    {

        $categories = $this->categoryModel->with(['childCategories', 'parentCategories'])
            ->latest('id')->paginate(5);

        return view('manager.category.index', compact('categories'));

    }


    public function create()
    {
        $categories =  $this->categoryModel->get(['id', 'name']);

        return view('manager.category.create', compact('categories'));


    }



    public function store(Request $request)
    {
        $dataCreate =  $request->all();
        $this->categoryModel->create($dataCreate);

        return redirect()->route('category.index')->with('message', 'Create category success');

    }


    public function show($id)
    {
        $category = $this->categoryModel->findOrFail($id);

        return  response()->json([
            'status'=>200,
            'data' =>new CategoryResource($category)
        ]);

    }




    public function edit($id)
    {
       $category= Category::findOrFail($id);
        $categories = $this->categoryModel->get(['id','name']);
        return view('manager.category.edit')->with(['category'=> $category,'categories'=>$categories]);
    }

    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);


        $dataUpdate = $request->all();


        $category->update($dataUpdate);

        return redirect()->route('category.index')->with('message', 'Edit category success');
    }


    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        return redirect()->route('category.index')->with('message', 'Delete category success');
    }
}

app/Http/Controllers/Manager/CouponController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Http\Requests\Coupon\CreateCouponRequest;
use App\Http\Requests\Coupon\UpdateCouponRequest;
use App\Traits\HandleImageTrait;
use App\Models\User;
use App\Models\Coupon;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;


class CouponController extends Controller
{
    public function index()
    {
        $coupons = Coupon::paginate(3);

        return view('manager.coupon.index')->with( 'coupons',$coupons);
    }


    public function create()
    {
        return view('manager.coupon.create');

    }

    public function store(Request  $request)
    {

        $dataCreate = $request->all();

        Coupon::create($dataCreate);

        return redirect()->route('coupon.index')->with('message', 'Create coupon success');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $coupon = Coupon::findOrFail($id);

        return view('manager.coupon.edit')->with('coupon', $coupon);
    }


    public function update(Request  $request, $id)
    {
        $coupon = Coupon::findOrFail($id);


        $dataUpdate = $request->all();


        $coupon->update($dataUpdate);

        return redirect()->route('coupon.index')->with('message', 'Edit coupon success');
    }

    public function destroy($id)
    {
        $coupon = Coupon::findOrFail($id);
        $coupon->delete();

        //Thực hiện chuyển trang
        return redirect()->route('coupon.index')->with('message', 'Delete coupon success');
    }
}

app/Http/Controllers/Manager/DashboardController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Coupon;
use App\Models\Order;
use App\Models\Product;
use App\Traits\HandleImageTrait;
use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{

    use HandleImageTrait;

    protected $categoryModel;
    protected $productModel;
    protected $userModel;
    protected $couponModel;
    protected $orderModel;


    public function __construct(Product $product,Category $categories, User $user, Coupon $coupons, Order $orders)
    {

        $this->categoryModel = $categories;
        $this->productModel = $product;
        $this->userModel = $user;
        $this->couponModel = $coupons;
        $this->orderModel = $orders;

    }

    public function index()
    {


        $products =  $this->productModel->count();
        $categories = $this->categoryModel->count();
        $user = $this->userModel->count();
        $coupons = $this->couponModel->count();
        $orders = $this->orderModel->count();

        return view('manager.dashboard.index', compact('products','user','categories','coupons','orders'));

    }

}

app/Http/Controllers/Manager/OrderManageController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Cart;
use App\Models\Category;
use App\Models\Coupon;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\Product;
use Illuminate\Http\Request;

class OrderManageController extends Controller
{
    protected  $categoryModel;
    protected  $productModel;
    protected  $cart;
    protected  $coupon;
    protected  $order;
    protected  $orderDetail;


    public function __construct(Category $categoryModel,Product $product, Cart $cart, Coupon $coupon, Order $order, OrderDetail $orderDetail)
    {
        $this->categoryModel = $categoryModel;
        $this->productModel = $product;
        $this->cart = $cart;
        $this->coupon = $coupon;
        $this->orderDetail = $orderDetail;
        $this->order = $order;
    }

    public function index(Request $request)
    {
        $orders = $this->order->with(['orderDetails'])->latest('id')->paginate(10);

        return view('manager.order.index', compact('orders'));
    }

    public function show($id)
    {
        $order = $this->order->with(['orderDetails', 'orderDetails.product'])->findOrFail($id);

        return view('manager.order.show', compact('order'));
    }
}

app/Http/Controllers/Manager/ProductController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\Product\CreateProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Traits\HandleImageTrait;
use App\Models\Product;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Str;


class ProductController extends Controller
{
    use HandleImageTrait;

    protected $path;
    protected $categoryModel;
    protected $productModel;



    public function __construct(Product $product,Category $categoryModel)
    {

        $this->categoryModel = $categoryModel;
        $this->productModel = $product;
        $this->path = 'upload/';
    }

    public function index(Request  $request)
    {
        $data['name'] = $request->name ?? null;
        $data['category_id'] = $request->category_id ?? null;

        $products =  $this->productModel->withName($data['name'])
            ->withCategoryId($data['category_id'])
            ->with(['categories'])
            ->latest('id')->paginate(5);


        return view('manager.product.index', compact('products'));

    }

    public function create()
    {
        $categories =  $this->categoryModel->get(['id', 'name']);

        return view('manager.product.create', compact('categories'));


    }


    public function store(Request  $request)
    {
        $image = $request->file('image');
        $dataCreate =  $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $product = $this->productModel->create($dataCreate);

        $product->assignCategories($dataCreate['category_ids']);

        return redirect()->route('product.index')->with('message', 'Create product success');

    }


    public function show($id)
    {


    }


    public function edit($id){
        $product = $this->productModel->with(['categories'])->findOrFail($id);
        $categories = $this->categoryModel->get();
        $listCategoryIds = $product->categories->pluck('id')->toArray();
        return view('manager.product.edit')->with(['product'=> $product,'categories'=>$categories,'listCategoryIds'=>$listCategoryIds]);
    }




    public function update(Request $request, $id)
    {
        $product = $this->productModel->findOrFail($id);
        $image = $request->file('image');
        $dataUpdate = $request->all();
        $dataUpdate['image'] = $this->updateImage($image, $this->path, $product->image);
        $product->update($dataUpdate);
        $product->assignCategories($request -> listCategoryIds);
        return redirect()->route('product.index')->with('message', 'Edit product success');
    }

    public function destroy($id)
    {
        $product = $this->productModel->findOrFail($id);
        $product->delete();

        //Thực hiện chuyển trang
        return redirect()->route('product.index')->with('message', 'Delete product success');
    }
}

app/Http/Controllers/Manager/RoleController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\Coupon;
use Illuminate\Http\Request;
use App\Models\Role;

class RoleController extends Controller
{
    protected $roleModel;

    /**
     * RolerController constructor.
     * @param $roleModel
     */

    public function __construct(Role $roleModel)
    {
        $this->roleModel = $roleModel;
    }


    public function index()
    {
        $roles = $this->roleModel->where('name','!=', 'super-admin')->paginate(5);

        return view('manager.role.index')->with( 'roles',$roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manager.role.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dataCreate = $request->all();

        Role::create($dataCreate);

        return redirect()->route('roles.index')->with('message', 'Create role success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Traits\HandleImageTrait;
use App\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    use HandleImageTrait;

    protected $path;
    protected $roleModel;

    protected $userModel;

    public function __construct(User $user, Role $role)
    {
        $this->userModel = $user;
        $this->path = 'upload/';
        $this->roleModel = $role;
    }



    public function index()
    {

        $users = $this->userModel->with('roles')->latest('id')->paginate(5);

        return view('manager.user.index')->with( 'users',$users);

    }


    public function create()
    {
        $roles = $this->roleModel->where('name', '!=', 'super-admin')->get();
        return view('manager.user.create', compact('roles'));
    }


    public function store(CreateUserRequest $request)
    {

        $image = $request->file('image');

        $dataCreate = $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $user =$this->userModel->create($dataCreate);
        $user->syncRoles($request->roles);
        return redirect()->route('users.index')->with('message', 'Create user success');
    }


    public function show($id)
    {
        //
    }



    public function edit($id)
    {
        $user = $this->userModel->with('roles')->findOrFail($id);

        $roles = $this->roleModel->where('name', '!=', 'super-admin')->get();
        $listRoleIds = $user->roles->pluck('id')->toArray();
        return view('manager.user.edit')->with(['user'=> $user, 'roles' =>$roles, 'listRoleIds' =>$listRoleIds]);
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $user = $this->userModel->findOrFail($id);
        $image = $request->file('image');

        $dataUpdate = $request->all();

        $dataUpdate['image'] = $this->updateImage($image, $this->path, $user->image);

        $user->update($dataUpdate);
        $user->syncRoles($request->roles);
        return redirect()->route('users.index')->with('message', 'Edit user success');

    }


    public function destroy($id)
    {
        $users = $this->userModel->findOrFail($id);
        $users->delete();

        //Thực hiện chuyển trang        //Thực hiện chuyển trang
        return redirect()->route('users.index')->with('message', 'Delete user success');
    }
}

resources/views/manager/coupon/create.blade.php
@extends('manager.layout.app')

@section('title', 'Create Coupons')

@section('content')
    <a class="btn btn-rose " href="{{route('coupon.index')}}">
      <span class="material-icons text-white">
        arrow_back
      </span>
    </a>
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-rose card-header-icon">
                <div class="card-icon">
                    <span class="material-icons">
                        aspect_ratio
                        </span>
                </div>
                <h4 class="card-title">Create Coupon</h4>
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('coupon.store') }}"  >
                    @csrf


                    <div class="form-group row">
                        <div class="col-md-6">
                            <input id="code" type="text" placeholder="{{ __('code') }}" class="form-control @error('code') is-invalid @enderror" name="code" value="{{ old('code') }}"  autocomplete="code" autofocus required>


                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <select class="selectpicker" data-live-search="true" name="type"  data-style="select-with-transition" required>
                                <option value="">Choose Type </option>

                                    <option value="Money">Money</option>
                                    <option value="Percent">Percent</option>
                            </select>


                        </div>
                    </div>


                    <div class="form-group row">
                        <div class="col-md-6">
                            <input id="value" type="number" placeholder="{{ __('value') }}" class="form-control @error('value') is-invalid @enderror" name="value" value="{{ old('value') }}"  autocomplete="value" autofocus required>

                        </div>
                    </div>
                   <div class="form-group row">
                        <div class="col-md-6">
                            <input id="quantity" type="number" placeholder="{{ __('quantity') }}" class="form-control @error('quantity') is-invalid @enderror" name="quantity" value="{{ old('quantity') }}"  autocomplete="quantity" autofocus required>


                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-6">
                            <input id="expiry_date" type="date" placeholder="{{ __('expiry_date') }}" class="form-control @error('expiry_date') is-invalid @enderror" name="expiry_date" value="{{ old('expiry_date') }}"  autocomplete="expery_date" autofocus required>

                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-rose">
                                {{ __('Create Coupon') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/manager/coupon/edit.blade.php
@extends('manager.layout.app')

@section('title', 'Edit Coupons')

@section('content')
    <a class="btn btn-rose " href="{{route('coupon.index')}}">
      <span class="material-icons text-white">
        arrow_back
      </span>
    </a>
    <div class="row justify-content-center">
        <div class="col-md-12 ">
            <div class="card ">
                <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon">
                        <span class="material-icons">
                            aspect_ratio
                            </span>
                    </div>
                    <h4 class="card-title">Edit Coupon</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('coupon.update', $coupon->id) }}"   >
                        @csrf
                        @method('put')

                        <div class="form-group row">
                            <label for="code" class="col-md-4 col-form-label">{{ __('code') }}</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control @error('code') is-invalid @enderror" name="code" value="{{ $coupon->code }}"  autocomplete="code" autofocus required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="expiry_date" class="col-md-4 col-form-label">{{ __('expiry_date') }}</label>

                            <div class="col-md-6">
                                <input id="expiry_date" type="text" class="form-control @error('expiry_date') is-invalid @enderror" name="expiry_date" value="{{ $coupon->expiry_date }}"  autocomplete="expiry_date" autofocus required>

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="quantity" class="col-md-4 col-form-label">{{ __('quantity') }}</label>

                            <div class="col-md-6">
                                <input id="quantity" type="text" class="form-control @error('quantity') is-invalid @enderror" name="quantity" value="{{ $coupon->quantity }}"  autocomplete="quantity" autofocus required>

                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="type" class="col-md-4 col-form-label">{{ __('type') }}</label>

                            <div class="col-md-6">
                                <input id="type" type="text" class="form-control @error('type') is-invalid @enderror" name="type" value="{{ $coupon->type }}"  autocomplete="type" autofocus required>

                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="value" class="col-md-4 col-form-label">{{ __('value') }}</label>

                            <div class="col-md-6">
                                <input id="value" type="text" class="form-control @error('value') is-invalid @enderror" name="value" value="{{ $coupon->value }}"  autocomplete="value" autofocus required>
                            </div>
                        </div>




                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-rose">
                                    {{ __('Edit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/manager/coupon/index.blade.php
@extends('manager.layout.app')

@section('title', 'Coupon')

@section('content')
    <h1 class="text-center" style="color: #e91e63; margin-bottom: 50px;  font-weight: 400;">LIST COUPON</h1>
    <div class="col-md-12">
        <a class="btn btn-rose" href="{{route('coupon.create')}}"><span class="material-icons">
            add_circle_outline 
            </span> Create Coupon</a>
        <div class="card">
          <div class="card-header card-header-rose card-header-icon">
            <div class="card-icon">
              <i class="material-icons">assignment</i>
            </div>
            <h4 class="card-title">Coupon Table</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th class="text-center">N.o</th>
                    <th>Code</th>
                    <th>Quantity</th>
                    <th>Type</th>
                    <th>Value</th>
                    <th class="text-right">Expery Date</th>
                    <th class="text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
            @foreach($coupons as $coupon)

    
                  <tr>
                    <td class="text-center">{{$loop->iteration}}</td>
                    <td>{{$coupon->code}}</td>
                    <td>{{$coupon->quantity}}</td>
                    <td>{{$coupon->type}}</td>
                    <td>{{$coupon->value}}</td>
                    <td class="td-actions text-right">{{$coupon->expiry_date}}</td>
                    <td class="td-actions text-right">
                    <a class="btn btn-success" href="{{route('coupon.edit', $coupon->id)}}"><i class="material-icons">edit</i></a>
                    <form action="{{route('coupon.destroy', $coupon->id)}}"  method="post" style="display: inline">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger " type="submit"style="background-color: #e91e63"><i class="material-icons">close</i></button>
    
                    </form>
                    </td>
                  </tr>
            @endforeach
                  
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    <script>

        @if(session('message'))
        alert("{{session('message')}}");
        @endif
    </script>
    <div>
        {{ $coupons->links() }}
    </div>

@endsection