routes/web.php
<?php

use Illuminate\Support\Facades\Route;




Route::group(['middleware'=>'auth'],function(){


Route::group(['prefix'=>'manager', 'namespace'=>'Manager'],function(){


    Route::resource('dashboard', 'DashboardController');
    Route::resource('users', 'UserController');

    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::resource('coupon', 'CouponController');
    Route::resource('roles', 'RoleController');

    Route::get('orders', 'OrderManageController@index')->name('manager.orders.index');
    Route::get('orders/{id}', 'OrderManageController@show')->name('manager.orders.show');


});

//client

    // Route::resource('cart', 'CartController');

    // Route::resource('checkout', 'CartController');



});
//


Route::group(['namespace'=>'Client'],function(){

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/products/{id}', 'HomeController@showProduct')->name('client.show_product');

    Route::get('/carts', 'CartController@index')->name('cart.index');

    Route::post('/add-to-cart', 'CartController@addToCart')->name('cart.add_to');

    Route::post('/change-to-cart', 'CartController@changeQuantityCart')->name('cart.change_quantity');

    Route::get('/orders', 'OrderController@index')->name('orders.index');


    Route::post('/add-coupon-order', 'OrderController@addCouponToOrder')->name('orders.add_coupon');


    Route::post('/orders', 'OrderController@store')->name('orders.store');

    Route::get('/order-list', 'OrderController@list')->name('orders.list');


    Route::get('/contact', 'ContactController@index')->name('contact');

    Route::get('/profile', 'ProfileController@index')->name('profile');
    Route::get('/profile-edit', 'ProfileController@edit')->name('profile.edit');
    Route::get('/profile-update', 'ProfileController@update')->name('profile.update');

});

Auth::routes();

app/User.php
<?php

namespace App;

use App\Traits\HandleImageTrait;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use HandleImageTrait;


    protected $table = 'users';

    protected $fillable = [
        'name', 'email', 'password', 'phone', 'address', 'gender', 'image'
    ];


    protected $hidden = [
        'password', 'remember_token',
    ];


    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function setPasswordAttribute($value)
    {
        return $this->attributes['password'] = Hash::make($value);
    }

}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;
use App\Traits\HandleImageTrait;
use App\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    use HandleImageTrait;

    protected $path;
    protected $roleModel;

    protected $userModel;

    public function __construct(User $user, Role $role)
    {
        $this->userModel = $user;
        $this->path = 'upload/';
        $this->roleModel = $role;
    }



    public function index()
    {

        $users = $this->userModel->with('roles')->latest('id')->paginate(5);

        return view('manager.user.index')->with( 'users',$users);

    }


    public function create()
    {
        $roles = $this->roleModel->where('name', '!=', 'super-admin')->get();
        return view('manager.user.create', compact('roles'));
    }


    public function store(CreateUserRequest $request)
    {

        $image = $request->file('image');

        $dataCreate = $request->all();
        $dataCreate['image'] = $this->saveImage($image, $this->path);
        $user =$this->userModel->create($dataCreate);
        $user->syncRoles($request->roles);
        return redirect()->route('users.index')->with('message', 'Create user success');
    }


    public function show($id)
    {
        //
    }



    public function edit($id)
    {
        $user = $this->userModel->with('roles')->findOrFail($id);

        $roles = $this->roleModel->where('name', '!=', 'super-admin')->get();
        $listRoleIds = $user->roles->pluck('id')->toArray();
        return view('manager.user.edit')->with(['user'=> $user, 'roles' =>$roles, 'listRoleIds' =>$listRoleIds]);
    }

    public function update(UpdateUserRequest $request, $id)
    {
        $user = $this->userModel->findOrFail($id);
        $image = $request->file('image');

        $dataUpdate = $request->all();

        $dataUpdate['image'] = $this->updateImage($image, $this->path, $user->image);

        $user->update($dataUpdate);
        $user->syncRoles($request->roles);
        return redirect()->route('users.index')->with('message', 'Edit user success');

    }


    public function destroy($id)
    {
        $users = $this->userModel->findOrFail($id);
        $users->delete();

        //Thực hiện chuyển trang        //Thực hiện chuyển trang
        return redirect()->route('users.index')->with('message', 'Delete user success');
    }
}

resources/views/user/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <title>@yield('title')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token()}}">
@include('user.layout.style')
</head>
<body class="goto-here">
@include('user.layout.navbar')


@yield('content')


<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
<hr>
@include('user.layout.footer')
@include('user.layout.js')

</body>
</html>

resources/views/user/layout/footer.blade.php
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Vegefoods</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Menu</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Shop</a></li>
                        <li><a href="#" class="py-2 d-block">About</a></li>
                        <li><a href="#" class="py-2 d-block">Journal</a></li>
                        <li><a href="#" class="py-2 d-block">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Help</h2>
                    <div class="d-flex">
                        <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                            <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
                            <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
                            <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
                            <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                        </ul>
                        <ul class="list-unstyled">
                            <li><a href="#" class="py-2 d-block">FAQs</a></li>
                            <li><a href="#" class="py-2 d-block">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">139 An Duong Vuong, Hue, Viet Nam</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+84 695 04 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">vegefood@email.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

resources/views/user/layout/js.blade.php
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="{{ asset('manager/asset/js/application.js') }}" type="text/javascript"></script>
<script src="{{asset('user/asset/js/jquery.min.js')}}"></script>
<script src="{{asset('user/asset/js/jquery-migrate-3.0.1.min.js')}}"></script>
<script src="{{asset('user/asset/js/popper.min.js')}}"></script>
<script src="{{asset('user/asset/js/bootstrap.min.js')}}"></script>
<script src="{{asset('user/asset/js/jquery.easing.1.3.js')}}"></script>
<script src="{{asset('user/asset/js/jquery.waypoints.min.js')}}"></script>
<script src="{{asset('user/asset/js/jquery.stellar.min.js')}}"></script>
<script src="{{asset('user/asset/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('user/asset/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{asset('user/asset/js/aos.js')}}"></script>
<script src="{{asset('user/asset/js/jquery.animateNumber.min.js')}}"></script>
<script src="{{asset('user/asset/js/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('user/asset/js/scrollax.min.js')}}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{{asset('user/asset/js/google-map.js')}}"></script>
<script src="{{asset('user/asset/js/main.js')}}"></script>
<!-- Forms Validations Plugin -->
<script src="{{ asset('manager/asset/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/jquery.bootstrap-wizard.js') }}"></script>
<script src="{{ asset('manager/asset/js/bootstrap-selectpicker.js') }}"></script>
<script src="{{ asset('manager/asset/js/bootstrap-datetimepicker.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/bootstrap-tagsinput.js') }}"></script>
<script src="{{ asset('manager/asset/js/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/fullcalendar.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/jquery-jvectormap.js') }}"></script>
<script src="{{ asset('manager/asset/js/nouislider.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/core.js') }}"></script>
<script src="{{ asset('manager/asset/js/arrive.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/chartist.min.js') }}"></script>
<script src="{{ asset('manager/asset/js/bootstrap-notify.js') }}"></script>
<script src="{{ asset('manager/asset/js/material-dashboard.js') }}" type="text/javascript"></script>
<script src="{{ asset('manager/asset/demo/demo.js') }}" type="text/javascript"></script>
<script src="{{ asset('manager/asset/js/application.js') }}" type="text/javascript"></script>
<script>
    $(document).ready(function(){

        var quantitiy=0;
        $('.quantity-right-plus').click(function(e){
            e.preventDefault();
            var quantity = parseInt($('#quantity').val());
            $('#quantity').val(quantity + 1);
        });

        $('.quantity-left-minus').click(function(e){
            e.preventDefault();
            var quantity = parseInt($('#quantity').val());
            if(quantity>0){
                $('#quantity').val(quantity - 1);
            }
        });

    });
</script>
<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    $(document).ready(function () {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts()

        md.initVectorMap()

        md.initFormExtendedDatetimepickers();
        if ($('.slider').length != 0) {
            md.initSliders();
        }

        $('[data-toggle="popover"]').popover()

        $(document).ready(function () {
            // Initialise the wizard
            demo.initMaterialWizard()
            setTimeout(function () {
                $('.card.card-wizard').addClass('active')
            }, 600)
        })
    })


    $(() => {

        $(document).on('click', '.change-quantity', function (event) {
            event.preventDefault();

            let product_id = $(this).data('product_id');
            let url = $(this).data('action');
            // let quantity = $(this).data('quantity');
            let quantity = $(this).data('quantity');

            $.ajax({
                url: url,
                data: {
                    product_id,
                    quantity
                },
                method: 'post'
            }).then((response) => {
                let {data} = response;
                if (data.quantity <= 0) {
                    $(`#cart-box-${data.id}`).remove();
                } else {
                    $(`#quantity${data.id}`).text(data.quantity)
                    $(`#total${data.id}`).text(+data.quantity * (+data.product.price))
                }
            })
                .catch(error => {

                })
        });


    })


</script>
@yield('script')

resources/views/user/layout/navbar.blade.php
<div class="py-1 bg-primary">
    <div class="container">
        <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
            <div class="col-lg-12 d-block">
                <div class="row d-flex">
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span
                                class="icon-phone2"></span></div>
                        <span class="text">+84 695 04 210</span>
                    </div>
                    <div class="col-md pr-4 d-flex topper align-items-center">
                        <div class="icon mr-2 d-flex justify-content-center align-items-center"><span
                                class="icon-paper-plane"></span></div>
                        <span class="text">vegefood@email.com</span>
                    </div>
                    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                        <span class="text">3-5 Business days delivery &amp; Free Returns</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar"
     style="font-size: 18px!important;">
    <div class="container">
        <a class="navbar-brand" href="{{route('home')}}">Vegefoods</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{{route('home')}}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{{route('contact')}}" class="nav-link">Contact</a></li>
                <li class="nav-item"><a href="{{route('orders.list')}}" class="nav-link">Checkout</a></li>
                <li class="nav-item cta cta-colored"><a href="{{route('cart.index')}}" class="nav-link">
                        @if(!empty(auth()->user()->id))
                        <span class="icon-shopping_cart notify"  id="cart-total-navbar">[{{$cartTotal}}]</span></a></li>
                @else
                        <span class="icon-shopping_cart notify"  id="cart-total-navbar">[0]</span></a></li>
                {{--                <li class="nav-item cta cta-colored"><a href="cart.html" class="nav-link"><span class="icon-shopping_cart"></span>[0]</a></li>--}}
            @endif
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}"><i class="fa fa-user"></i>{{ __('Login') }}</a>
                    </li>

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}"> <i
                                    class="fa fa-user-plus"></i> {{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    @if(Auth::user()->email == 'cuong021099@gmail.com')
                        <li class="nav-item ">
                            <a href="{{ route('dashboard.index') }}" class="nav-link"><i class="fa fa-tasks"></i>
                                Manage</a>
                        </li>
                    @endif
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('profile')}}">
                            {{-- <i class="icon-user"></i> --}}
                            <img src="{{asset('upload/'.auth()->user() ->image)}}" alt="..."
                            style="width: 20px; height: 20px; border-radius: 100%; ">
                            {{ Auth::user()->name }}
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="fa fa-sign-out"></i>
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->
{{-- <script>

    $(() => {
        $(document).on('click', 'button.deletebtn', function () {
            $(this).closest('tr').remove();
            return false;
        });
        $(document).on('click', '.change-quantity', function (event) {
            event.preventDefault();

            let product_id = $(this).data('product_id');
            let url = $(this).data('action');
            // let quantity = $(this).data('quantity');
            let quantity = $(this).data('quantity');

            $.ajax({
                url: url,
                data: {
                    product_id,
                    quantity
                },
                method: 'post'
            }).then((response) => {
                let {data} = response;
                if (data.quantity <= 0) {
                    $(`#cart-box-${data.id}`).remove();
                } else {
                    $(`#quantity${data.id}`).text(data.quantity)
                    $(`#total${data.id}`).text(+data.quantity * (+data.product.price))
                }
            })
                .catch(error => {

                })
        });


    })



</script> --}}

resources/views/user/layout/style.blade.php
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
{{--<link href="{{ asset('manager/asset/css/material-dashboard.css') }}" rel="stylesheet"/>--}}

<link rel="stylesheet" href="{{asset('user/asset/css/open-iconic-bootstrap.min.css')}} ">
<link rel="stylesheet" href="{{asset('user/asset/css/animate.css')}}">

<link rel="stylesheet" href="{{asset('user/asset/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('user/asset/css/owl.theme.default.min.css')}}">
<link rel="stylesheet" href="{{asset('user/asset/css/magnific-popup.css')}}">

<link rel="stylesheet" href="{{asset('user/asset/css/aos.css')}}">

<link rel="stylesheet" href="{{asset('user/asset/css/ionicons.min.css')}}">

<link rel="stylesheet" href="{{asset('user/asset/css/bootstrap-datepicker.css')}}">
<link rel="stylesheet" href="{{asset('user/asset/css/jquery.timepicker.css')}}">


<link rel="stylesheet" href="{{asset('user/asset/css/flaticon.css')}}">
<link rel="stylesheet" href="{{asset('user/asset/css/icomoon.css')}}">
<link rel="stylesheet" href="{{asset('user/asset/css/style.css')}}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
@yield('style')